version: '3'
services:
  web:
    image: server
    container_name: web
    command: bash -c "gunicorn project.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
    networks:
      - server

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./cert/certbot/conf:/etc/letsencrypt
      - ./cert/certbot/www:/var/www/certbot
      - /home/ubuntu/hackaton/images:/home/ubuntu/hackaton/images # 이미지 파일 디렉토리를 마운트
      - ./staticfiles:/app/staticfiles 
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - server
    command: /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./cert/certbot/conf:/etc/letsencrypt
      - ./cert/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
    depends_on:
      - web
    networks:
      - server

networks:
  server:
