# Generated by Django 5.0.7 on 2024-07-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
