# Generated by Django 5.0.7 on 2024-07-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
