# Generated by Django 5.0.7 on 2024-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='close',
            field=models.DateTimeField(),
        ),
    ]
