# Generated by Django 5.0.7 on 2024-07-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0002_alter_post_close'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type1',
            new_name='type',
        ),
    ]
