# Generated by Django 5.0.7 on 2024-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0003_rename_type1_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='close',
            field=models.CharField(max_length=20),
        ),
    ]
