# Generated by Django 5.0.7 on 2024-07-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0009_rename_boss_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
