# Generated by Django 5.0.7 on 2024-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_customuser_location_customuser_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(default='01090343359'),
            preserve_default=False,
        ),
    ]
