# Generated by Django 5.0.7 on 2024-07-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
