# Generated by Django 5.0.7 on 2024-07-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_remove_customuser_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
